package UpdateDeleteForm;

import Forms.ManagerForm;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.management.system.*;

public class UD_ProjectForm extends javax.swing.JFrame 
{

    static ManagerForm MF = new ManagerForm();
    
    
    public UD_ProjectForm() 
    {
        initComponents();
        
        if (ReadFile.getInstance().DepartmentNums != 0)
        {
           for (int i = 0; i < ReadFile.getInstance().DepartmentNums; i++)
            {
                jComboBox1.addItem(ReadFile.getInstance().DEPARTMENT.get(i).getName().toString());
            }
        }
        
        ProjId.setEditable(false);
        ProjName.setEditable(false);
        
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        BackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        ProjId = new javax.swing.JTextField();
        ProjName = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        DeleteBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(20, 30, 100, 32);

        jLabel1.setText("Project ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 160, 90, 16);

        jLabel2.setText("Project Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 160, 90, 16);

        jLabel3.setText("Department ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 160, 90, 16);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(390, 200, 100, 26);
        getContentPane().add(ProjId);
        ProjId.setBounds(70, 200, 100, 24);

        ProjName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ProjNameActionPerformed(evt);
            }
        });
        getContentPane().add(ProjName);
        ProjName.setBounds(230, 200, 100, 24);

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn);
        SaveBtn.setBounds(230, 310, 100, 32);

        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(575, 100, 100, 26);

        jLabel4.setText("Select Project  you want to Update or Delete");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 50, 260, 16);

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DeleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBtn);
        DeleteBtn.setBounds(60, 310, 100, 32);

        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewBtn);
        ViewBtn.setBounds(577, 150, 100, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BackBtnActionPerformed
    {//GEN-HEADEREND:event_BackBtnActionPerformed
        ProjId.setEditable(false);
        ProjId.setText(null);
        ProjName.setEditable(false);
        ProjName.setText(null);
        MF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveBtnActionPerformed
    {//GEN-HEADEREND:event_SaveBtnActionPerformed
        
        if (ProjId.getText().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Select Project!", "Field not entered", JOptionPane.WARNING_MESSAGE);
        } 
        else
        {
            //other logic
        }
        
        
        
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ProjNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ProjNameActionPerformed
    {//GEN-HEADEREND:event_ProjNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProjNameActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DeleteBtnActionPerformed
    {//GEN-HEADEREND:event_DeleteBtnActionPerformed
        
        if (ProjId.getText().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Select Project!", "Field not entered", JOptionPane.WARNING_MESSAGE);
        } 
        else
        {
            //other logic
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ViewBtnActionPerformed
    {//GEN-HEADEREND:event_ViewBtnActionPerformed
        ProjId.setEditable(true);
        ProjName.setEditable(true);

        String SelectedProject  = jComboBox2.getSelectedItem().toString();

        for (int i = 0; i < ReadFile.getInstance().ProjectNums; i++)
        {
            if (ReadFile.getInstance().PROJECT.get(i).getName() == SelectedProject)
            {
                ProjId.setText(String.valueOf(ReadFile.getInstance().PROJECT.get(i).getID()));
                ProjName.setText(ReadFile.getInstance().PROJECT.get(i).getName());
                break;
            }
        }
        
    }//GEN-LAST:event_ViewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UD_ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UD_ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UD_ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UD_ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new UD_ProjectForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField ProjId;
    private javax.swing.JTextField ProjName;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
