package UpdateDeleteForm;

import Forms.AdminForm;
import java.io.IOException;
import javax.swing.JOptionPane;
import project.management.system.*;
import project.management.system.EditFile;

public class UD_ProjectForm extends javax.swing.JFrame 
{

    static AdminForm MF = new AdminForm();
    
    
    public UD_ProjectForm() 
    {
        initComponents();

        ProjectNameTxt.setEditable(false);
        
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        BackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProjectIdTxt = new javax.swing.JTextField();
        ProjectNameTxt = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        DeleteBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        DepartmentTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(40, 20, 100, 32);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Project ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 140, 90, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Project Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 140, 90, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Department ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 140, 90, 16);

        ProjectIdTxt.setEditable(false);
        getContentPane().add(ProjectIdTxt);
        ProjectIdTxt.setBounds(40, 180, 100, 24);

        ProjectNameTxt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ProjectNameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(ProjectNameTxt);
        ProjectNameTxt.setBounds(170, 180, 100, 24);

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn);
        SaveBtn.setBounds(390, 310, 100, 32);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(540, 70, 100, 26);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select Project  you want to Update or Delete");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 30, 260, 16);

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DeleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBtn);
        DeleteBtn.setBounds(250, 310, 100, 32);

        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewBtn);
        ViewBtn.setBounds(540, 190, 100, 32);

        DepartmentTxt.setEditable(false);
        getContentPane().add(DepartmentTxt);
        DepartmentTxt.setBounds(300, 180, 100, 24);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Project Background.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1, 0, 720, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BackBtnActionPerformed
    {//GEN-HEADEREND:event_BackBtnActionPerformed
        jComboBox1.removeAllItems();
        DepartmentTxt.setText(null);
        ProjectIdTxt.setText(null);
        ProjectNameTxt.setEditable(false);
        ProjectNameTxt.setText(null);
        MF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveBtnActionPerformed
    {//GEN-HEADEREND:event_SaveBtnActionPerformed
        String ID = ProjectIdTxt.getText().toString();
        String Name = ProjectNameTxt.getText().toString();
        
        String DepartmentID = DepartmentTxt.getText().toString();
        
        if (ProjectIdTxt.getText().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Select Project!", "Field not entered", JOptionPane.WARNING_MESSAGE);
        } 
        else
        {
            for (int i = 0; i < ReadFile.ProjectNums; i++)
            {
                if (Integer.parseInt(ID) ==  ReadFile.PROJECT.get(i).getID())
                {
                    try
                    {//+2 (File Description Line + Indexing from zero)
                        EditFile.deleteProject(i + 2);
                        WriteFile.writeProject(ID, Name, DepartmentID);
                        ReadFile.clearAllClasses();
                        ReadFile.fileLines();
                        ReadFile.readAllClasses();
                        JOptionPane.showMessageDialog(this, "congratulations Project Updated Successfully", "Updated", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    } 
                    catch (IOException ex)
                    {
                    }
                }
            }
           
            jComboBox1.removeAllItems();
            ProjectIdTxt.setText(null);
            ProjectNameTxt.setEditable(false);
            ProjectNameTxt.setText(null);
            MF.setVisible(true);
            this.dispose();
        }
        
        
        
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ProjectNameTxtActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ProjectNameTxtActionPerformed
    {//GEN-HEADEREND:event_ProjectNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProjectNameTxtActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DeleteBtnActionPerformed
    {//GEN-HEADEREND:event_DeleteBtnActionPerformed
        String ID = ProjectIdTxt.getText().toString();
        
        if (ID.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Select Project!", "Field not entered", JOptionPane.WARNING_MESSAGE);
        } 
        else
        {
            for (int i = 0; i < ReadFile.ProjectNums; i++)
            {
                if (Integer.parseInt(ID) ==  ReadFile.PROJECT.get(i).getID())
                {
                    try
                    {//+2 (File Description Line + Indexing from zero)
                        EditFile.deleteProject(i + 2);
                        ReadFile.clearAllClasses();
                        ReadFile.fileLines();
                        ReadFile.readAllClasses();
                        JOptionPane.showMessageDialog(this, "congratulations Project Deleted Successfully", "Deleted", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    } 
                    catch (IOException ex)
                    {
                        //Logger.getLogger(UD_ResourcesForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }                
            }
            jComboBox1.removeAllItems();
            ProjectIdTxt.setText(null);
            ProjectNameTxt.setEditable(false);
            ProjectNameTxt.setText(null);
            MF.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ViewBtnActionPerformed
    {//GEN-HEADEREND:event_ViewBtnActionPerformed
        ProjectNameTxt.setEditable(true);

        String SelectedProject  = jComboBox1.getSelectedItem().toString();

        for (int i = 0; i < ReadFile.ProjectNums; i++)
        {
            if (ReadFile.PROJECT.get(i).getName() == SelectedProject)
            {
                ProjectIdTxt.setText(String.valueOf(ReadFile.PROJECT.get(i).getID()));
                ProjectNameTxt.setText(ReadFile.PROJECT.get(i).getName());
                DepartmentTxt.setText(String.valueOf(ReadFile.PROJECT.get(i).getDepartmentID()));
                break;
            }
        }
        
    }//GEN-LAST:event_ViewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UD_ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UD_ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UD_ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UD_ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new UD_ProjectForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField DepartmentTxt;
    private javax.swing.JTextField ProjectIdTxt;
    private javax.swing.JTextField ProjectNameTxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton ViewBtn;
    public static javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
