package Forms;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.management.system.Department;
import project.management.system.ReadFile;
import project.management.system.WriteFile;

public class DepartmentForm extends javax.swing.JFrame
{
    static ManagerForm MF = new ManagerForm();
    
    public DepartmentForm()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        BackBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DepartmentNameTxt = new javax.swing.JTextField();
        DepartmentIdTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(40, 20, 90, 32);

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn);
        SaveBtn.setBounds(570, 350, 90, 32);

        jLabel1.setText("Department Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 110, 120, 16);

        jLabel2.setText("Department ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 110, 120, 16);
        getContentPane().add(DepartmentNameTxt);
        DepartmentNameTxt.setBounds(420, 170, 110, 24);
        getContentPane().add(DepartmentIdTxt);
        DepartmentIdTxt.setBounds(200, 170, 110, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BackBtnActionPerformed
    {//GEN-HEADEREND:event_BackBtnActionPerformed
        SaveBtn.setVisible(true);
        DepartmentIdTxt.setEditable(true);
        DepartmentNameTxt.setEditable(true);
        DepartmentIdTxt.setText(null);
        DepartmentNameTxt.setText(null);
        MF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveBtnActionPerformed
    {//GEN-HEADEREND:event_SaveBtnActionPerformed
        String ID = DepartmentIdTxt.getText().toString();
        String Name = DepartmentNameTxt.getText().toString();
        
        if (ID.isEmpty() || Name.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter All Empty Fields!", "Field not entered", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            for (int i = 0; i < ReadFile.DepartmentNums; i++)
            {
                if (Integer.parseInt(ID) == ReadFile.DEPARTMENT.get(i).getID())
                {
                    JOptionPane.showMessageDialog(this, "Enter Unique ID!", "Department ID is already saved", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            try
            {
                WriteFile.getInstance().writeDepartment(ID, Name);
            } 
            catch (IOException ex)
            {
                Logger.getLogger(ResourcesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            DepartmentIdTxt.setEditable(false);
            DepartmentNameTxt.setEditable(false);
            SaveBtn.setVisible(false);
            
        }
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField DepartmentIdTxt;
    private javax.swing.JTextField DepartmentNameTxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
