package Forms;

import javax.swing.JOptionPane;
import project.management.system.ReadFile;



public class EmployeeForm extends javax.swing.JFrame
{
    
    public EmployeeForm()
    {
        initComponents();
        
        //System.out.println(LoginForm.accFoundID);
        
        
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ViewTaskBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProjectIdTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DepartmentIdTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        WelcomeLabel = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        SaveBtn = new javax.swing.JButton();
        ToDate = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        ViewTaskBtn.setText("View Task");
        ViewTaskBtn.setPreferredSize(new java.awt.Dimension(90, 40));
        ViewTaskBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ViewTaskBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewTaskBtn);
        ViewTaskBtn.setBounds(270, 200, 80, 40);

        ViewBtn.setText("View Project");
        ViewBtn.setPreferredSize(new java.awt.Dimension(90, 40));
        ViewBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewBtn);
        ViewBtn.setBounds(480, 320, 130, 40);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(270, 150, 80, 26);

        jLabel1.setText("Task ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 110, 50, 16);

        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(620, 150, 80, 26);

        jLabel2.setText("Task Status:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 150, 80, 16);

        jLabel3.setText("Project ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 150, 70, 16);

        ProjectIdTxt.setEditable(false);
        getContentPane().add(ProjectIdTxt);
        ProjectIdTxt.setBounds(400, 200, 100, 24);

        jLabel4.setText("Department ID:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 150, 90, 16);

        DepartmentIdTxt.setEditable(false);
        getContentPane().add(DepartmentIdTxt);
        DepartmentIdTxt.setBounds(520, 200, 100, 24);

        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login background.png"))); // NOI18N
        jLabel5.setText("asd");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 0, 20, 480);

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Manage Tasks");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 60, 83, 16);

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("View Projects");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(500, 60, 79, 16);

        jLabel8.setText("To Date:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 150, 50, 16);

        jLabel9.setText("Project Name:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(610, 110, 80, 16);

        WelcomeLabel.setText("Welcome,");
        getContentPane().add(WelcomeLabel);
        WelcomeLabel.setBounds(10, 20, 70, 16);

        NameTxt.setEditable(false);
        getContentPane().add(NameTxt);
        NameTxt.setBounds(70, 20, 110, 24);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("In Progress");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(120, 220, 98, 28);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Done");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(130, 190, 61, 28);

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn);
        SaveBtn.setBounds(100, 320, 130, 32);
        getContentPane().add(ToDate);
        ToDate.setBounds(10, 200, 100, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewTaskBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ViewTaskBtnActionPerformed
    {//GEN-HEADEREND:event_ViewTaskBtnActionPerformed
        int TaskID = Integer.valueOf(jComboBox1.getSelectedItem().toString());
        
        
        for (int i = 0; i < ReadFile.TaskNums; i++)
        {
            if (ReadFile.TASK.get(i).getID() == TaskID)
            {
                ToDate.setText(ReadFile.getInstance().TASK.get(i).getToDate().toString());
                break;
            }
        }
        
        
        
        
        
        
    }//GEN-LAST:event_ViewTaskBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ViewBtnActionPerformed
    {//GEN-HEADEREND:event_ViewBtnActionPerformed
         String ProjectName = jComboBox2.getSelectedItem().toString();
         String ProjectID;
         String DepartmentID;
         
        
        for (int i = 0; i < ReadFile.ProjectNums; i++)
        {
            if (ProjectName == ReadFile.PROJECT.get(i).getName())
            {
                ProjectIdTxt.setText(String.valueOf(ReadFile.PROJECT.get(i).getID()));
                DepartmentIdTxt.setText(String.valueOf(ReadFile.PROJECT.get(i).getDepartmentID()));
                break;
            }
        }
        
        
        
        
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton1ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveBtnActionPerformed
    {//GEN-HEADEREND:event_SaveBtnActionPerformed
        String done = "Done";
        String inProgress = "In Progress";
        if (!jRadioButton1.isSelected() && !jRadioButton2.isSelected())
        {
            JOptionPane.showMessageDialog(this, "You Have To Select At Lease One", "Select One", JOptionPane.WARNING_MESSAGE);
        }
        else
        {

            if (jRadioButton1.isSelected())
            {
                System.out.println(done);
            }
            if (jRadioButton2.isSelected())
            {
                System.out.println(inProgress);
            }
            
        
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DepartmentIdTxt;
    public static javax.swing.JTextField NameTxt;
    private javax.swing.JTextField ProjectIdTxt;
    private javax.swing.JButton SaveBtn;
    private datechooser.beans.DateChooserCombo ToDate;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton ViewTaskBtn;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
