package Forms;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.management.system.ReadFile;



public class EmployeeForm extends javax.swing.JFrame
{
    
    public EmployeeForm()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        ViewTaskBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProjectIdTxtProject = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DepartmentIdTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        WelcomeLabel = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        TaskStatus = new javax.swing.JCheckBox();
        ToDateTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ProjectIdTxtTask = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        ViewTaskBtn.setText("View Task");
        ViewTaskBtn.setPreferredSize(new java.awt.Dimension(90, 40));
        ViewTaskBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ViewTaskBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewTaskBtn);
        ViewTaskBtn.setBounds(170, 150, 110, 40);

        ViewBtn.setText("View Project");
        ViewBtn.setPreferredSize(new java.awt.Dimension(90, 40));
        ViewBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewBtn);
        ViewBtn.setBounds(560, 150, 110, 40);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(50, 150, 80, 26);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("All in Progress Task IDs:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 100, 140, 20);

        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(430, 150, 80, 26);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Task Status:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 240, 100, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Project ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 240, 100, 16);

        ProjectIdTxtProject.setEditable(false);
        getContentPane().add(ProjectIdTxtProject);
        ProjectIdTxtProject.setBounds(410, 290, 100, 24);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Department ID:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 240, 100, 16);

        DepartmentIdTxt.setEditable(false);
        getContentPane().add(DepartmentIdTxt);
        DepartmentIdTxt.setBounds(570, 290, 100, 24);

        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login background.png"))); // NOI18N
        jLabel5.setText("asd");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 0, 20, 480);

        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Manage Tasks");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 10, 83, 16);

        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("View Projects");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(630, 10, 79, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("To Date:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 240, 80, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Project Name:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(510, 100, 80, 16);

        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setText("Welcome,");
        getContentPane().add(WelcomeLabel);
        WelcomeLabel.setBounds(10, 20, 70, 16);

        NameTxt.setEditable(false);
        getContentPane().add(NameTxt);
        NameTxt.setBounds(80, 20, 110, 24);

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn);
        SaveBtn.setBounds(110, 380, 130, 32);

        TaskStatus.setText("Is It Done?");
        getContentPane().add(TaskStatus);
        TaskStatus.setBounds(250, 290, 87, 24);

        ToDateTxt.setEditable(false);
        getContentPane().add(ToDateTxt);
        ToDateTxt.setBounds(10, 290, 100, 24);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Project ID:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 240, 70, 16);

        ProjectIdTxtTask.setEditable(false);
        getContentPane().add(ProjectIdTxtTask);
        ProjectIdTxtTask.setBounds(130, 290, 100, 24);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gradient-4.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-2, 0, 720, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewTaskBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ViewTaskBtnActionPerformed
    {//GEN-HEADEREND:event_ViewTaskBtnActionPerformed
        int TaskID = Integer.valueOf(jComboBox1.getSelectedItem().toString());
        
        for (int i = 0; i < ReadFile.TaskNums; i++)
        {
            if (ReadFile.TASK.get(i).getID() == TaskID)
            {
                ProjectIdTxtTask.setText(String.valueOf(ReadFile.TASK.get(i).getProjectID()));
                ToDateTxt.setText(ReadFile.TASK.get(i).getToDate().toString());
                break;
            }
        }       
    }//GEN-LAST:event_ViewTaskBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ViewBtnActionPerformed
    {//GEN-HEADEREND:event_ViewBtnActionPerformed
         String ProjectName = jComboBox2.getSelectedItem().toString();
         String ProjectID;
         String DepartmentID;
         
        
        for (int i = 0; i < ReadFile.ProjectNums; i++)
        {
            if (ProjectName == ReadFile.PROJECT.get(i).getName())
            {
                ProjectIdTxtProject.setText(String.valueOf(ReadFile.PROJECT.get(i).getID()));
                DepartmentIdTxt.setText(String.valueOf(ReadFile.PROJECT.get(i).getDepartmentID()));
                break;
            }
        }
        
        
        
        
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveBtnActionPerformed
    {//GEN-HEADEREND:event_SaveBtnActionPerformed
        String done = "Done";
        String inProgress = "In Progress";
        /*if (!jRadioButton1.isSelected() && !jRadioButton2.isSelected())
        {
            JOptionPane.showMessageDialog(this, "You Have To Select At Lease One", "Select One", JOptionPane.WARNING_MESSAGE);
        }
        else
        {

            if (jRadioButton1.isSelected())
            {
                System.out.println(done);
            }
            if (jRadioButton2.isSelected())
            {
                System.out.println(inProgress);
            }
            
        
        }*/
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DepartmentIdTxt;
    public static javax.swing.JTextField NameTxt;
    private javax.swing.JTextField ProjectIdTxtProject;
    private javax.swing.JTextField ProjectIdTxtTask;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JCheckBox TaskStatus;
    private javax.swing.JTextField ToDateTxt;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton ViewTaskBtn;
    private javax.swing.JLabel WelcomeLabel;
    public static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
