package Forms;

import javax.swing.JOptionPane;
import Forms.SignUpForm;
public class LoginForm extends javax.swing.JPanel
{

    static SignUpForm SignObj = new SignUpForm();
    public LoginForm()
    {
        //JOptionPane.showMessageDialog(null, "Thank you using our system", "Logout Successfully", JOptionPane.INFORMATION_MESSAGE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JButton();
        SignUpBtn = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("User Name:");
        add(jLabel1);
        jLabel1.setBounds(130, 110, 100, 16);

        jLabel2.setText("Password:");
        add(jLabel2);
        jLabel2.setBounds(130, 180, 100, 16);
        add(jTextField1);
        jTextField1.setBounds(280, 120, 150, 24);
        add(jTextField2);
        jTextField2.setBounds(280, 180, 150, 24);

        LoginBtn.setText("Login");
        add(LoginBtn);
        LoginBtn.setBounds(480, 260, 90, 40);

        SignUpBtn.setText("Sign Up");
        SignUpBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SignUpBtnActionPerformed(evt);
            }
        });
        add(SignUpBtn);
        SignUpBtn.setBounds(554, 37, 100, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SignUpBtnActionPerformed
    {//GEN-HEADEREND:event_SignUpBtnActionPerformed
        SignObj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SignUpBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton SignUpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
