package Forms;
import UpdateDeleteForm.*;
import javax.swing.JOptionPane;
import project.management.system.ReadFile;

public class ManagerForm extends javax.swing.JFrame
{

    static PrintTaskForm PTF = new PrintTaskForm();
    static TaskForm TF = new TaskForm();
    static DepartmentForm DF = new DepartmentForm();
    static ResourcesForm RF = new ResourcesForm();
    static LogProgressForm LPF = new LogProgressForm();
    static ProjectForm PF = new ProjectForm();

    static UD_DepartmentForm UDDF = new UD_DepartmentForm();
    static UD_ProjectForm UDPF = new UD_ProjectForm();
    static UD_ResourcesForm UDRF = new UD_ResourcesForm();
    static UD_TaskForm UDTF = new UD_TaskForm();
    
    
    public ManagerForm()
    {
        initComponents();
        NameTxt.setText("ADMIN");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        PrintTaskBtn = new javax.swing.JButton();
        LogBtn = new javax.swing.JButton();
        AddTaskBtn = new javax.swing.JButton();
        UD_TaskBtn = new javax.swing.JButton();
        AddDepartmentBtn = new javax.swing.JButton();
        UD_DepartmentBtn = new javax.swing.JButton();
        AddResourceBtn = new javax.swing.JButton();
        UD_ResourceBtn = new javax.swing.JButton();
        AddProjectBtn = new javax.swing.JButton();
        UD_ProjectBtn = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        PrintTaskBtn.setText("Print Tasks & Projects");
        PrintTaskBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PrintTaskBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PrintTaskBtn);
        PrintTaskBtn.setBounds(440, 80, 200, 35);

        LogBtn.setText("Log Progress");
        LogBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LogBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogBtn);
        LogBtn.setBounds(100, 80, 200, 35);

        AddTaskBtn.setText("Add Task");
        AddTaskBtn.setMaximumSize(null);
        AddTaskBtn.setMinimumSize(null);
        AddTaskBtn.setName(""); // NOI18N
        AddTaskBtn.setOpaque(false);
        AddTaskBtn.setPreferredSize(null);
        AddTaskBtn.setRolloverEnabled(true);
        AddTaskBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddTaskBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddTaskBtn);
        AddTaskBtn.setBounds(100, 180, 200, 35);

        UD_TaskBtn.setText("Update / Delete Task");
        UD_TaskBtn.setMaximumSize(null);
        UD_TaskBtn.setMinimumSize(null);
        UD_TaskBtn.setName(""); // NOI18N
        UD_TaskBtn.setOpaque(false);
        UD_TaskBtn.setPreferredSize(null);
        UD_TaskBtn.setRolloverEnabled(true);
        UD_TaskBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UD_TaskBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UD_TaskBtn);
        UD_TaskBtn.setBounds(100, 240, 200, 35);

        AddDepartmentBtn.setText("Add Department");
        AddDepartmentBtn.setMaximumSize(null);
        AddDepartmentBtn.setMinimumSize(null);
        AddDepartmentBtn.setName(""); // NOI18N
        AddDepartmentBtn.setOpaque(false);
        AddDepartmentBtn.setPreferredSize(null);
        AddDepartmentBtn.setRolloverEnabled(true);
        AddDepartmentBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddDepartmentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddDepartmentBtn);
        AddDepartmentBtn.setBounds(100, 300, 200, 35);

        UD_DepartmentBtn.setText("Update / Delete  Department");
        UD_DepartmentBtn.setMaximumSize(null);
        UD_DepartmentBtn.setMinimumSize(null);
        UD_DepartmentBtn.setName(""); // NOI18N
        UD_DepartmentBtn.setOpaque(false);
        UD_DepartmentBtn.setPreferredSize(null);
        UD_DepartmentBtn.setRolloverEnabled(true);
        UD_DepartmentBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UD_DepartmentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UD_DepartmentBtn);
        UD_DepartmentBtn.setBounds(100, 360, 200, 35);

        AddResourceBtn.setText("Add Resource");
        AddResourceBtn.setMaximumSize(null);
        AddResourceBtn.setMinimumSize(null);
        AddResourceBtn.setName(""); // NOI18N
        AddResourceBtn.setOpaque(false);
        AddResourceBtn.setPreferredSize(null);
        AddResourceBtn.setRolloverEnabled(true);
        AddResourceBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddResourceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddResourceBtn);
        AddResourceBtn.setBounds(440, 180, 200, 35);

        UD_ResourceBtn.setText("Update / Delete Resource");
        UD_ResourceBtn.setMaximumSize(null);
        UD_ResourceBtn.setMinimumSize(null);
        UD_ResourceBtn.setName(""); // NOI18N
        UD_ResourceBtn.setOpaque(false);
        UD_ResourceBtn.setPreferredSize(null);
        UD_ResourceBtn.setRolloverEnabled(true);
        UD_ResourceBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UD_ResourceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UD_ResourceBtn);
        UD_ResourceBtn.setBounds(440, 240, 200, 35);

        AddProjectBtn.setText("Add Project");
        AddProjectBtn.setMaximumSize(null);
        AddProjectBtn.setMinimumSize(null);
        AddProjectBtn.setName(""); // NOI18N
        AddProjectBtn.setOpaque(false);
        AddProjectBtn.setPreferredSize(null);
        AddProjectBtn.setRolloverEnabled(true);
        AddProjectBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddProjectBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddProjectBtn);
        AddProjectBtn.setBounds(440, 300, 200, 35);

        UD_ProjectBtn.setText("Update / Delete Project");
        UD_ProjectBtn.setMaximumSize(null);
        UD_ProjectBtn.setMinimumSize(null);
        UD_ProjectBtn.setName(""); // NOI18N
        UD_ProjectBtn.setOpaque(false);
        UD_ProjectBtn.setPreferredSize(null);
        UD_ProjectBtn.setRolloverEnabled(true);
        UD_ProjectBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UD_ProjectBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UD_ProjectBtn);
        UD_ProjectBtn.setBounds(440, 360, 200, 35);

        WelcomeLabel.setText("Welcome,");
        getContentPane().add(WelcomeLabel);
        WelcomeLabel.setBounds(10, 20, 70, 16);

        NameTxt.setEditable(false);
        getContentPane().add(NameTxt);
        NameTxt.setBounds(70, 20, 110, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LogBtnActionPerformed
    {//GEN-HEADEREND:event_LogBtnActionPerformed
        LPF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogBtnActionPerformed

    private void AddTaskBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AddTaskBtnActionPerformed
    {//GEN-HEADEREND:event_AddTaskBtnActionPerformed
        if (ReadFile.MemberNums == 0)
        {
            JOptionPane.showMessageDialog(this, "No Employees Were Added", "Sorry Form Can't Be Loaded", JOptionPane.WARNING_MESSAGE);
        }
        else if (ReadFile.ResourceNums == 0)
        {
            JOptionPane.showMessageDialog(this, "No Resources Were Added", "Sorry Form Can't Be Loaded", JOptionPane.WARNING_MESSAGE);
        }
        else if (ReadFile.ProjectNums == 0)
        {
            JOptionPane.showMessageDialog(this, "No Projects Were Added", "Sorry Form Can't Be Loaded", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
           TF.setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_AddTaskBtnActionPerformed

    private void AddDepartmentBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AddDepartmentBtnActionPerformed
    {//GEN-HEADEREND:event_AddDepartmentBtnActionPerformed
        DF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddDepartmentBtnActionPerformed

    private void AddResourceBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AddResourceBtnActionPerformed
    {//GEN-HEADEREND:event_AddResourceBtnActionPerformed
        RF.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_AddResourceBtnActionPerformed

    private void AddProjectBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AddProjectBtnActionPerformed
    {//GEN-HEADEREND:event_AddProjectBtnActionPerformed
        if (ReadFile.DepartmentNums == 0)
        {
            JOptionPane.showMessageDialog(this, "No Departments Were Added", "Sorry Form Can't Be Loaded", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            PF.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_AddProjectBtnActionPerformed

    private void UD_TaskBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UD_TaskBtnActionPerformed
    {//GEN-HEADEREND:event_UD_TaskBtnActionPerformed
        if (ReadFile.TaskNums == 0)
        {
            JOptionPane.showMessageDialog(null, "No Tasks Were Added!", "Add Task First", JOptionPane.ERROR_MESSAGE);
        }
        else
        {   
            for (int i = 0; i < ReadFile.TaskNums; i++)
            {
                UDTF.jComboBox1.addItem(String.valueOf(ReadFile.getInstance().TASK.get(i).getID()));
            }
            UDTF.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_UD_TaskBtnActionPerformed

    private void UD_ResourceBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UD_ResourceBtnActionPerformed
    {//GEN-HEADEREND:event_UD_ResourceBtnActionPerformed
        if (ReadFile.ResourceNums == 0)
        {
            JOptionPane.showMessageDialog(null, "No Resources Were Added!", "Add Resource First", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            for (int i = 0; i < ReadFile.ResourceNums; i++)
            {
                UDRF.jComboBox1.addItem(ReadFile.RESOURCE.get(i).getName().toString());
            }
            UDRF.setVisible(true);
            this.dispose();
            
        }
    }//GEN-LAST:event_UD_ResourceBtnActionPerformed

    private void UD_DepartmentBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UD_DepartmentBtnActionPerformed
    {//GEN-HEADEREND:event_UD_DepartmentBtnActionPerformed
        if (ReadFile.DepartmentNums == 0)
        {
            JOptionPane.showMessageDialog(null, "No Departments Were Added!", "Add Department First", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            for (int i = 0; i < ReadFile.DepartmentNums; i++)
            {
                UDDF.jComboBox1.addItem(ReadFile.DEPARTMENT.get(i).getName().toString());
            }
            UDDF.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_UD_DepartmentBtnActionPerformed

    private void UD_ProjectBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UD_ProjectBtnActionPerformed
    {//GEN-HEADEREND:event_UD_ProjectBtnActionPerformed
        
        if (ReadFile.ProjectNums != 0)
        {
            for (int i = 0; i < ReadFile.ProjectNums; i++)
            {
                 UDPF.jComboBox1.addItem(ReadFile.PROJECT.get(i).getName().toString());
            }
            UDPF.setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No Projects Were Added!", "Add Project First", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UD_ProjectBtnActionPerformed

    private void PrintTaskBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PrintTaskBtnActionPerformed
    {//GEN-HEADEREND:event_PrintTaskBtnActionPerformed
        if (ReadFile.TaskNums != 0)
        {
           for (int i = 0; i < ReadFile.TaskNums; i++)
           {
                PrintTaskForm.jComboBox1.addItem(ReadFile.TASK.get(i).getID());
           }
           PTF.setVisible(true);
           this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No Projects Were Added!", "Add Project First", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PrintTaskBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDepartmentBtn;
    private javax.swing.JButton AddProjectBtn;
    private javax.swing.JButton AddResourceBtn;
    private javax.swing.JButton AddTaskBtn;
    private javax.swing.JButton LogBtn;
    public static javax.swing.JTextField NameTxt;
    private javax.swing.JButton PrintTaskBtn;
    private javax.swing.JButton UD_DepartmentBtn;
    private javax.swing.JButton UD_ProjectBtn;
    private javax.swing.JButton UD_ResourceBtn;
    private javax.swing.JButton UD_TaskBtn;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
