package Forms;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.management.system.ReadFile;
import project.management.system.WriteFile;

public class ProjectForm extends javax.swing.JFrame 
{

    static AdminForm MF = new AdminForm();
    
    public ProjectForm() 
    {
        initComponents();
        
        if (ReadFile.DepartmentNums != 0)
        {
           for (int i = 0; i < ReadFile.DepartmentNums; i++)
            {
                jComboBox1.addItem(String.valueOf(ReadFile.DEPARTMENT.get(i).getID()));
            }
        }
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        BackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        ProjectIdTxt = new javax.swing.JTextField();
        ProjectNameTxt = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(40, 20, 100, 32);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Project ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 140, 90, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Project Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 140, 90, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Department ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 140, 100, 16);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(300, 180, 100, 26);
        getContentPane().add(ProjectIdTxt);
        ProjectIdTxt.setBounds(40, 180, 100, 24);
        getContentPane().add(ProjectNameTxt);
        ProjectNameTxt.setBounds(170, 180, 100, 24);

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn);
        SaveBtn.setBounds(390, 310, 100, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Project Background.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1, 0, 720, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BackBtnActionPerformed
    {//GEN-HEADEREND:event_BackBtnActionPerformed
        SaveBtn.setVisible(true);
        ProjectIdTxt.setEditable(true);
        ProjectNameTxt.setEditable(true);
        ProjectIdTxt.setText(null);
        ProjectNameTxt.setText(null);
        MF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveBtnActionPerformed
    {//GEN-HEADEREND:event_SaveBtnActionPerformed
        String ID = ProjectIdTxt.getText().toString();
        String Name = ProjectNameTxt.getText().toString();
        
        String DepartmentID;
        DepartmentID = jComboBox1.getSelectedItem().toString();

        if (ID.isEmpty() || Name.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter All Empty Fields!", "Field not entered", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            for (int i = 0; i < ReadFile.ProjectNums; i++)
            {
                if (Integer.parseInt(ID) == ReadFile.PROJECT.get(i).getID())
                {
                    JOptionPane.showMessageDialog(this, "Enter Unique ID!", "Project ID is already saved", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            try
            {
                WriteFile.writeProject(ID, Name, DepartmentID);
                ReadFile.clearAllClasses();
                ReadFile.fileLines();
                ReadFile.readAllClasses();
            } 
            catch (IOException ex)
            {
                Logger.getLogger(ResourcesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            ProjectIdTxt.setEditable(false);
            ProjectNameTxt.setEditable(false);
            SaveBtn.setVisible(false);
        }
   
    }//GEN-LAST:event_SaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new ProjectForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField ProjectIdTxt;
    private javax.swing.JTextField ProjectNameTxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
