package Forms;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.management.system.ReadFile;
import project.management.system.Resource;
import project.management.system.WriteFile;

public class ResourcesForm extends javax.swing.JFrame
{

    static ManagerForm MF = new ManagerForm();
    
    public ResourcesForm()
    {
        initComponents();
        
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ResourceNameTxt = new javax.swing.JTextField();
        ResourceIdTxt = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        jLabel1.setText("Resource Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 120, 100, 16);

        jLabel2.setText("Resource ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 120, 90, 16);
        getContentPane().add(ResourceNameTxt);
        ResourceNameTxt.setBounds(410, 170, 90, 24);
        getContentPane().add(ResourceIdTxt);
        ResourceIdTxt.setBounds(210, 170, 90, 24);

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn);
        SaveBtn.setBounds(560, 310, 100, 32);

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(40, 30, 100, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveBtnActionPerformed
    {//GEN-HEADEREND:event_SaveBtnActionPerformed
        String ID = ResourceIdTxt.getText().toString();
        String Name = ResourceNameTxt.getText().toString();
        if (ID.isEmpty() || Name.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter All Empty Fields!", "Field not entered", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            for (int i = 0; i < ReadFile.ResourceNums; i++)
            {
                if (Integer.parseInt(ID) == ReadFile.RESOURCE.get(i).getID())
                {
                    JOptionPane.showMessageDialog(this, "Enter Unique ID!", "Resouce ID is already saved", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            try
            {
                WriteFile.getInstance().writeResource(ID, Name);
            } 
            catch (IOException ex)
            {
                Logger.getLogger(ResourcesForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            ResourceIdTxt.setEditable(false);
            ResourceNameTxt.setEditable(false);
            SaveBtn.setVisible(false);
        }
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BackBtnActionPerformed
    {//GEN-HEADEREND:event_BackBtnActionPerformed
        SaveBtn.setVisible(true);
        ResourceIdTxt.setEditable(true);
        ResourceNameTxt.setEditable(true);
        ResourceIdTxt.setText(null);
        ResourceNameTxt.setText(null);
        MF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ResourcesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ResourcesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ResourcesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ResourcesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ResourcesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField ResourceIdTxt;
    private javax.swing.JTextField ResourceNameTxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
