package Forms;

import project.management.system.Employee;
import project.management.system.TeamMember;
import project.management.system.ReadFile;
import project.management.system.WriteFile;

import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
 
public class SignUpForm extends javax.swing.JFrame 
{

    static LoginForm LG = new LoginForm();
    TeamMember TM = new TeamMember();
    
    

    /**
     * Creates new form SignUpForm
     */
    public SignUpForm() 
    {
        initComponents();
        
        IdTxt.setEditable(false);
        BackBtn.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    SignUpForm(LoginForm aThis) 
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        AddressTxt = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        EmailTxt = new javax.swing.JTextField();
        IdTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PasswordTxt = new javax.swing.JTextField();
        PhoneTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        MailFormatTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 90, 50, 16);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 210, 70, 16);

        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 90, 60, 16);

        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 140, 50, 16);

        NameTxt.setMaximumSize(null);
        NameTxt.setMinimumSize(new java.awt.Dimension(70, 70));
        NameTxt.setName(""); // NOI18N
        NameTxt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                NameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NameTxt);
        NameTxt.setBounds(130, 120, 100, 25);

        AddressTxt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddressTxtActionPerformed(evt);
            }
        });
        getContentPane().add(AddressTxt);
        AddressTxt.setBounds(440, 120, 100, 25);

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn);
        SaveBtn.setBounds(560, 380, 100, 32);

        BackBtn.setText("Back To Main Menu");
        BackBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(14, 17, 150, 32);
        getContentPane().add(EmailTxt);
        EmailTxt.setBounds(210, 170, 100, 25);
        getContentPane().add(IdTxt);
        IdTxt.setBounds(290, 350, 100, 25);

        jLabel5.setText("Your ID will Show Up Here");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 310, 150, 16);
        getContentPane().add(PasswordTxt);
        PasswordTxt.setBounds(440, 240, 100, 25);

        PhoneTxt.setMaximumSize(null);
        PhoneTxt.setMinimumSize(new java.awt.Dimension(70, 70));
        PhoneTxt.setName(""); // NOI18N
        getContentPane().add(PhoneTxt);
        PhoneTxt.setBounds(130, 240, 100, 25);

        jLabel6.setText("Phone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 210, 36, 16);

        MailFormatTxt.setEditable(false);
        MailFormatTxt.setText("@management.sys.com");
        MailFormatTxt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MailFormatTxtActionPerformed(evt);
            }
        });
        getContentPane().add(MailFormatTxt);
        MailFormatTxt.setBounds(310, 170, 150, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveBtnActionPerformed
    {//GEN-HEADEREND:event_SaveBtnActionPerformed
        String ID = String.valueOf(TM.giveId());
        System.out.println("Your ID is: " + TM.giveId());
        IdTxt.setText(ID);
        
        String Name = NameTxt.getText().toString();
        String Address = AddressTxt.getText().toString();
        String Phone = PhoneTxt.getText().toString();
        String Email = EmailTxt.getText().toString() + MailFormatTxt.getText().toString();
        String Password = PasswordTxt.getText().toString();
        
        
        if (Name.isEmpty() || Address.isEmpty() || Phone.isEmpty() || Password.isEmpty() || Email.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter All Empty Fields!", "Field not entered", JOptionPane.WARNING_MESSAGE);
        } 
        else
        {
            try
            {
                WriteFile.getInstance().writeMember(ID, Name, Address, Phone, Email, Password);
            } 
            catch (IOException ex)
            {
                //Logger.getLogger(SignUpForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            
            BackBtn.setVisible(true);
            SaveBtn.setVisible(false);
            
            NameTxt.setEditable(false);
            AddressTxt.setEditable(false);
            PhoneTxt.setEditable(false);
            PasswordTxt.setEditable(false);
            EmailTxt.setEditable(false);
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BackBtnActionPerformed
    {//GEN-HEADEREND:event_BackBtnActionPerformed
        LG.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void AddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTxtActionPerformed

    private void NameTxtActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_NameTxtActionPerformed
    {//GEN-HEADEREND:event_NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtActionPerformed

    private void MailFormatTxtActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MailFormatTxtActionPerformed
    {//GEN-HEADEREND:event_MailFormatTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailFormatTxtActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JTextField IdTxt;
    private javax.swing.JTextField MailFormatTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField PasswordTxt;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
